// Code generated by gen_phase_coverage.go. DO NOT EDIT.
//
// Source manifest: pkg/agent/phase_manifest.yaml (sections.phases).
// Build with: go generate ./pkg/tools/.../phase_policy_gen.go
// Regenerate: go run ./scripts/gen_phase_coverage -o pkg/tools pkg/agent/phase_manifest.yaml
//
// Phase 12.49: split into 3 files by build mode:
//   - phase_policy_table.go (this file) — canonical type + data table +
//     LifecycleAllowedAt + MustHaveCanonicalLifecycleKeys + PolicySchemaError +
//     SortedToolPhases. No build tag — compiled in BOTH modes.
//   - phase_policy.go (build tag `!strict_phases`) — default-mode lookup.
//   - phase_policy_strict.go (build tag `strict_phases`) — strict-mode lookup.
//
// This 3-way split keeps the data table canonical across modes (no manual
// duplication if we ever add a 6th phase) while letting the lookup function
// differ by mode.
package tools

import (
	"sort"

	"github.com/sipeed/picoclaw/pkg/phases"
)

// ToolVisibilityPolicy is the per-phase policy row that drives 3 dispatcher
// sites in pkg/tools: (site 1) resolver, (site 2) lifecycle gate,
// (site 3) toolAllowedLocked discovery suppression.
//
// Plan §3.1: ABSOLUTE row (Allowlist != nil) overrides base config; RELATIVE
// row (Allowlist == nil) unions base + BaseAdds. DiscoveryVisible gates the
// discovery-tool exemption (BM25/Regex) inside toolAllowedLocked.
//
// LifecycleAllowed: explicit 4 keys per row, fail-closed (missing key =
// blocked). Lifecycle gate (IsLifecycleToolAllowed) keys off this map.
//
// FailClosed (Plan §4.20 L3): row-level opt-in ONLY for non-sensitive sites.
type ToolVisibilityPolicy struct {
	Phase            string
	Allowlist        []string
	BaseAdds         []string
	LifecycleAllowed map[string]bool
	DiscoveryVisible bool
	FailClosed       bool
}

// toolPolicies is the canonical phase-keyed policy table for pkg/tools.
// Frozen post-Phase 12.47 (POST-FINAL added).
var toolPolicies = map[string]*ToolVisibilityPolicy{
	phases.PhaseSet: {
		Phase:            phases.PhaseSet,
		Allowlist:        []string{"set_goal"},
		BaseAdds:         nil,
		LifecycleAllowed: map[string]bool{"set_goal": true, "goal_progress": false, "view_goal": false, "complete_goal": true},
		DiscoveryVisible: false,
	},
	phases.PhaseOpen: {
		Phase:            phases.PhaseOpen,
		Allowlist:        nil,
		BaseAdds:         []string{"view_goal", "complete_goal"},
		LifecycleAllowed: map[string]bool{"set_goal": false, "goal_progress": false, "view_goal": true, "complete_goal": true},
		DiscoveryVisible: true,
	},
	phases.PhaseCheckpoint: {
		Phase:            phases.PhaseCheckpoint,
		Allowlist:        []string{"goal_progress", "complete_goal"},
		BaseAdds:         nil,
		LifecycleAllowed: map[string]bool{"set_goal": false, "goal_progress": true, "view_goal": false, "complete_goal": true},
		DiscoveryVisible: false,
	},
	phases.PhaseFinal: {
		Phase:            phases.PhaseFinal,
		Allowlist:        []string{"complete_goal"},
		BaseAdds:         nil,
		LifecycleAllowed: map[string]bool{"set_goal": false, "goal_progress": false, "view_goal": false, "complete_goal": true},
		DiscoveryVisible: false,
	},
	phases.PhasePostFinal: {
		Phase:            phases.PhasePostFinal,
		Allowlist:        []string{},
		BaseAdds:         nil,
		LifecycleAllowed: map[string]bool{"set_goal": false, "goal_progress": false, "view_goal": false, "complete_goal": false},
		DiscoveryVisible: false,
	},
}

// LifecycleAllowedAt reads LifecycleAllowed from the policy table.
func LifecycleAllowedAt(phase, tool string) bool {
	p := ToolPolicyForPhase(phase)
	if p == nil || p.LifecycleAllowed == nil {
		return false
	}
	allowed, ok := p.LifecycleAllowed[tool]
	return ok && allowed
}

// MustHaveCanonicalLifecycleKeys checks row schema invariants.
func MustHaveCanonicalLifecycleKeys(p *ToolVisibilityPolicy) error {
	if p == nil {
		return nil
	}
	if len(p.LifecycleAllowed) != len(lifecycleToolNames) {
		return &PolicySchemaError{Phase: p.Phase, Reason: "LifecycleAllowed size != 4"}
	}
	for _, k := range lifecycleToolNames {
		if _, ok := p.LifecycleAllowed[k]; !ok {
			return &PolicySchemaError{Phase: p.Phase, Reason: "missing key " + k}
		}
	}
	return nil
}

// PolicySchemaError is returned when schema invariant is broken.
type PolicySchemaError struct {
	Phase  string
	Reason string
}

func (e *PolicySchemaError) Error() string {
	return "policy schema error [phase=" + e.Phase + "]: " + e.Reason
}

// SortedToolPhases returns canonical phase tokens sorted alphabetically.
func SortedToolPhases() []string {
	out := make([]string, 0, len(toolPolicies))
	for _, p := range toolPolicies {
		out = append(out, p.Phase)
	}
	sort.Strings(out)
	return out
}
