// Code generated by gen_phase_coverage.go. DO NOT EDIT.
//
// Source manifest: pkg/agent/phase_manifest.yaml (sections.phases).
// Build with: go generate ./pkg/tools/.../phase_policy_gen.go
// Regenerate: go run ./scripts/gen_phase_coverage -o pkg/tools pkg/agent/phase_manifest.yaml
package tools

import (
	"sort"
	"strings"

	"github.com/sipeed/picoclaw/pkg/phases"
)

// ToolVisibilityPolicy is the per-phase policy row that drives 3 dispatcher
// sites in pkg/tools: (site 1) resolver, (site 2) lifecycle gate,
// (site 3) toolAllowedLocked discovery suppression.
//
// Plan §3.1: ABSOLUTE row (Allowlist != nil) overrides base config; RELATIVE
// row (Allowlist == nil) unions base + BaseAdds. DiscoveryVisible gates the
// discovery-tool exemption (BM25/Regex) inside toolAllowedLocked.
//
// LifecycleAllowed: explicit 4 keys per row, fail-closed (missing key =
// blocked). Lifecycle gate (IsLifecycleToolAllowed) keys off this map.
//
// FailClosed (Plan §4.20 L3): row-level opt-in ONLY for non-sensitive sites
// — sets the behavior when PolicyForPhase returned nil. The 2 sensitive
// sites (site 2/3 + recovery-evaluation in pkg/agent) hardcode their own
// strict-mode flag in code; they DO NOT honor FailClosed. Keep this field
// for future non-sensitive sites that want unknown-phase BLOCK instead of
// pass-through.
type ToolVisibilityPolicy struct {
	Phase            string
	Allowlist        []string           // nil = RELATIVE (base ∪ BaseAdds)
	BaseAdds         []string           // for RELATIVE rows
	LifecycleAllowed map[string]bool    // canonical 4 keys (set_goal/goal_progress/view_goal/complete_goal)
	DiscoveryVisible bool               // BM25/Regex exempt at this phase?
	FailClosed       bool               // row-level fail-closed opt-in (non-sensitive sites only)
}

// toolPolicies is the canonical phase-keyed policy table for pkg/tools.
// Frozen post-Phase 12.47 (POST-FINAL added). Plan §3.1 + §3.3 + §4.20 L2.
//
// Manifest source: pkg/agent/phase_manifest.yaml → gen_phase_coverage.go.
// Always cross-check generated table vs plan §3.1 when editing by hand.
var toolPolicies = map[string]*ToolVisibilityPolicy{
	phases.PhaseSet: {
		Phase: phases.PhaseSet,
		// ABSOLUTE: pin [set_goal] regardless of base. (Phase 11+12.3.1)
		Allowlist: []string{"set_goal"},
		BaseAdds:  nil,
		LifecycleAllowed: map[string]bool{
			"set_goal":      true,
			"goal_progress": false,
			"view_goal":     false,
			"complete_goal": true,
		},
		DiscoveryVisible: false, // lock discovery at SET (Phase 12.5)
	},
	phases.PhaseOpen: {
		Phase: phases.PhaseOpen,
		// RELATIVE: open = base ∪ [view_goal, complete_goal].
		// No `set_goal` (must call set_goal first), no `goal_progress` (only at CHECKPOINT).
		Allowlist: nil,
		BaseAdds:  []string{"view_goal", "complete_goal"},
		LifecycleAllowed: map[string]bool{
			"set_goal":      false,
			"goal_progress": false,
			"view_goal":     true,
			"complete_goal": true,
		},
		DiscoveryVisible: true, // exempt at OPEN
	},
	phases.PhaseCheckpoint: {
		Phase: phases.PhaseCheckpoint,
		// ABSOLUTE: pin [goal_progress, complete_goal] (Phase 11+12.14).
		Allowlist: []string{"goal_progress", "complete_goal"},
		BaseAdds:  nil,
		LifecycleAllowed: map[string]bool{
			"set_goal":      false,
			"goal_progress": true,
			"view_goal":     false,
			"complete_goal": true,
		},
		DiscoveryVisible: false, // lock discovery at CHECKPOINT (Phase 12.18)
	},
	phases.PhaseFinal: {
		Phase: phases.PhaseFinal,
		// ABSOLUTE: pin [complete_goal] (Phase 11+12.3.1).
		Allowlist: []string{"complete_goal"},
		BaseAdds:  nil,
		LifecycleAllowed: map[string]bool{
			"set_goal":      false,
			"goal_progress": false,
			"view_goal":     false,
			"complete_goal": true,
		},
		DiscoveryVisible: false,
	},
	phases.PhasePostFinal: {
		Phase: phases.PhasePostFinal,
		// ABSOLUTE non-nil empty (E2: nil = allow-all; non-nil empty = allow-zero).
		// All classes blocked (lifecycle, discovery, non-discovery). Hard guard
		// at top of toolAllowedLocked enforces this in code (R4-F2) — row here
		// is schema-contract only (T3c).
		Allowlist: []string{},
		BaseAdds:  nil,
		LifecycleAllowed: map[string]bool{
			"set_goal":      false,
			"goal_progress": false,
			"view_goal":     false,
			"complete_goal": false,
		},
		DiscoveryVisible: false,
	},
}

// ToolPolicyForPhase returns the canonical policy row for a phase token,
// or nil if phase is unknown / empty. Exposed publicly so pkg/tools tests
// can assert schema contract (T1 cells).
//
// NOTE: callers MUST handle nil. The 2 sensitive sites (IsLifecycleToolAllowed,
// toolAllowedLocked suppression path) treat nil as fail-CLOSED (R6-F1 L2).
// Non-sensitive sites (resolver, hint contributors) treat nil as fail-OPEN.
func ToolPolicyForPhase(phase string) *ToolVisibilityPolicy {
	if phase == "" {
		return nil
	}
	// Case-insensitive lookup — phase tokens are canonical lowercase but
	// guard against accidental capital-O fallout (cf. Phase 12.1 regression).
	return toolPolicies[strings.ToLower(strings.TrimSpace(phase))]
}

// LifecycleAllowedAt reports whether the lifecycle tool is allowed at the
// given phase, reading from the policy table (Plan §3.3 site 2).
//
// Fail-CLOSED: unknown / empty phase → false. Tool name outside the 4-key
// LifecycleAllowed map → false. Missing key in row's map → false.
//
// Callers MUST NOT use this for non-lifecycle tools (returns false for
// anything outside the 4 canonical tools). Site 2 (IsLifecycleToolAllowed)
// and site 3 (toolAllowedLocked suppression path) are the only intended
// callers.
func LifecycleAllowedAt(phase, tool string) bool {
	p := ToolPolicyForPhase(phase)
	if p == nil || p.LifecycleAllowed == nil {
		return false
	}
	allowed, ok := p.LifecycleAllowed[tool]
	return ok && allowed
}

// MustHaveCanonicalLifecycleKeys — schema invariant helper. Plan §3.1:
// every policy row's LifecycleAllowed map MUST have exactly 4 canonical keys
// (set_goal/goal_progress/view_goal/complete_goal). Missing keys = BLOCKED
// silently = bug. Used by tests (T1) AND by gen_phase_coverage validation.
func MustHaveCanonicalLifecycleKeys(p *ToolVisibilityPolicy) error {
	if p == nil {
		return nil
	}
	if len(p.LifecycleAllowed) != len(lifecycleToolNames) {
		return &PolicySchemaError{Phase: p.Phase, Reason: "LifecycleAllowed size != 4"}
	}
	for _, k := range lifecycleToolNames {
		if _, ok := p.LifecycleAllowed[k]; !ok {
			return &PolicySchemaError{Phase: p.Phase, Reason: "missing key " + k}
		}
	}
	return nil
}

// PolicySchemaError is returned by MustHaveCanonicalLifecycleKeys — its
// presence in a test indicates a manifest drift between generated table
// and canonical 4-tool set (Plan §4.20 L1 single-source guarantee).
type PolicySchemaError struct {
	Phase  string
	Reason string
}

func (e *PolicySchemaError) Error() string {
	return "policy schema error [phase=" + e.Phase + "]: " + e.Reason
}

// SortedToolPhases returns the canonical phase tokens sorted alphabetically.
// Convenience for test deterministic ordering + cross-table equality.
func SortedToolPhases() []string {
	out := make([]string, 0, len(toolPolicies))
	for _, p := range toolPolicies {
		out = append(out, p.Phase)
	}
	sort.Strings(out)
	return out
}
